// Northeast US counties for the pilot launch.
// Format: { county: "Berks County", state: "Pennsylvania", abbr: "PA" }
// Extend this list as coverage grows.

export type CountyEntry = {
  county: string;
  state: string;
  abbr: string;
};

export const NORTHEAST_COUNTIES: CountyEntry[] = [
  // Pennsylvania
  { county: "Adams County", state: "Pennsylvania", abbr: "PA" },
  { county: "Allegheny County", state: "Pennsylvania", abbr: "PA" },
  { county: "Beaver County", state: "Pennsylvania", abbr: "PA" },
  { county: "Berks County", state: "Pennsylvania", abbr: "PA" },
  { county: "Blair County", state: "Pennsylvania", abbr: "PA" },
  { county: "Bucks County", state: "Pennsylvania", abbr: "PA" },
  { county: "Butler County", state: "Pennsylvania", abbr: "PA" },
  { county: "Cambria County", state: "Pennsylvania", abbr: "PA" },
  { county: "Centre County", state: "Pennsylvania", abbr: "PA" },
  { county: "Chester County", state: "Pennsylvania", abbr: "PA" },
  { county: "Cumberland County", state: "Pennsylvania", abbr: "PA" },
  { county: "Dauphin County", state: "Pennsylvania", abbr: "PA" },
  { county: "Delaware County", state: "Pennsylvania", abbr: "PA" },
  { county: "Erie County", state: "Pennsylvania", abbr: "PA" },
  { county: "Franklin County", state: "Pennsylvania", abbr: "PA" },
  { county: "Lancaster County", state: "Pennsylvania", abbr: "PA" },
  { county: "Lebanon County", state: "Pennsylvania", abbr: "PA" },
  { county: "Lehigh County", state: "Pennsylvania", abbr: "PA" },
  { county: "Luzerne County", state: "Pennsylvania", abbr: "PA" },
  { county: "Lycoming County", state: "Pennsylvania", abbr: "PA" },
  { county: "Monroe County", state: "Pennsylvania", abbr: "PA" },
  { county: "Montgomery County", state: "Pennsylvania", abbr: "PA" },
  { county: "Northampton County", state: "Pennsylvania", abbr: "PA" },
  { county: "Philadelphia County", state: "Pennsylvania", abbr: "PA" },
  { county: "Pike County", state: "Pennsylvania", abbr: "PA" },
  { county: "Schuylkill County", state: "Pennsylvania", abbr: "PA" },
  { county: "Washington County", state: "Pennsylvania", abbr: "PA" },
  { county: "Westmoreland County", state: "Pennsylvania", abbr: "PA" },
  { county: "York County", state: "Pennsylvania", abbr: "PA" },
  // New York
  { county: "Albany County", state: "New York", abbr: "NY" },
  { county: "Bronx County", state: "New York", abbr: "NY" },
  { county: "Broome County", state: "New York", abbr: "NY" },
  { county: "Chemung County", state: "New York", abbr: "NY" },
  { county: "Dutchess County", state: "New York", abbr: "NY" },
  { county: "Erie County", state: "New York", abbr: "NY" },
  { county: "Fulton County", state: "New York", abbr: "NY" },
  { county: "Greene County", state: "New York", abbr: "NY" },
  { county: "Kings County", state: "New York", abbr: "NY" },
  { county: "Monroe County", state: "New York", abbr: "NY" },
  { county: "Nassau County", state: "New York", abbr: "NY" },
  { county: "New York County", state: "New York", abbr: "NY" },
  { county: "Niagara County", state: "New York", abbr: "NY" },
  { county: "Oneida County", state: "New York", abbr: "NY" },
  { county: "Onondaga County", state: "New York", abbr: "NY" },
  { county: "Orange County", state: "New York", abbr: "NY" },
  { county: "Orleans County", state: "New York", abbr: "NY" },
  { county: "Putnam County", state: "New York", abbr: "NY" },
  { county: "Queens County", state: "New York", abbr: "NY" },
  { county: "Rensselaer County", state: "New York", abbr: "NY" },
  { county: "Richmond County", state: "New York", abbr: "NY" },
  { county: "Rockland County", state: "New York", abbr: "NY" },
  { county: "Saratoga County", state: "New York", abbr: "NY" },
  { county: "Schenectady County", state: "New York", abbr: "NY" },
  { county: "Suffolk County", state: "New York", abbr: "NY" },
  { county: "Sullivan County", state: "New York", abbr: "NY" },
  { county: "Ulster County", state: "New York", abbr: "NY" },
  { county: "Warren County", state: "New York", abbr: "NY" },
  { county: "Washington County", state: "New York", abbr: "NY" },
  { county: "Westchester County", state: "New York", abbr: "NY" },
  // New Jersey
  { county: "Atlantic County", state: "New Jersey", abbr: "NJ" },
  { county: "Bergen County", state: "New Jersey", abbr: "NJ" },
  { county: "Burlington County", state: "New Jersey", abbr: "NJ" },
  { county: "Camden County", state: "New Jersey", abbr: "NJ" },
  { county: "Cape May County", state: "New Jersey", abbr: "NJ" },
  { county: "Cumberland County", state: "New Jersey", abbr: "NJ" },
  { county: "Essex County", state: "New Jersey", abbr: "NJ" },
  { county: "Gloucester County", state: "New Jersey", abbr: "NJ" },
  { county: "Hudson County", state: "New Jersey", abbr: "NJ" },
  { county: "Mercer County", state: "New Jersey", abbr: "NJ" },
  { county: "Middlesex County", state: "New Jersey", abbr: "NJ" },
  { county: "Monmouth County", state: "New Jersey", abbr: "NJ" },
  { county: "Morris County", state: "New Jersey", abbr: "NJ" },
  { county: "Ocean County", state: "New Jersey", abbr: "NJ" },
  { county: "Passaic County", state: "New Jersey", abbr: "NJ" },
  { county: "Somerset County", state: "New Jersey", abbr: "NJ" },
  { county: "Sussex County", state: "New Jersey", abbr: "NJ" },
  { county: "Union County", state: "New Jersey", abbr: "NJ" },
  { county: "Warren County", state: "New Jersey", abbr: "NJ" },
  // Connecticut
  { county: "Fairfield County", state: "Connecticut", abbr: "CT" },
  { county: "Hartford County", state: "Connecticut", abbr: "CT" },
  { county: "Litchfield County", state: "Connecticut", abbr: "CT" },
  { county: "Middlesex County", state: "Connecticut", abbr: "CT" },
  { county: "New Haven County", state: "Connecticut", abbr: "CT" },
  { county: "New London County", state: "Connecticut", abbr: "CT" },
  { county: "Tolland County", state: "Connecticut", abbr: "CT" },
  { county: "Windham County", state: "Connecticut", abbr: "CT" },
  // Massachusetts
  { county: "Barnstable County", state: "Massachusetts", abbr: "MA" },
  { county: "Berkshire County", state: "Massachusetts", abbr: "MA" },
  { county: "Bristol County", state: "Massachusetts", abbr: "MA" },
  { county: "Essex County", state: "Massachusetts", abbr: "MA" },
  { county: "Franklin County", state: "Massachusetts", abbr: "MA" },
  { county: "Hampden County", state: "Massachusetts", abbr: "MA" },
  { county: "Hampshire County", state: "Massachusetts", abbr: "MA" },
  { county: "Middlesex County", state: "Massachusetts", abbr: "MA" },
  { county: "Norfolk County", state: "Massachusetts", abbr: "MA" },
  { county: "Plymouth County", state: "Massachusetts", abbr: "MA" },
  { county: "Suffolk County", state: "Massachusetts", abbr: "MA" },
  { county: "Worcester County", state: "Massachusetts", abbr: "MA" },
  // Vermont
  { county: "Addison County", state: "Vermont", abbr: "VT" },
  { county: "Bennington County", state: "Vermont", abbr: "VT" },
  { county: "Caledonia County", state: "Vermont", abbr: "VT" },
  { county: "Chittenden County", state: "Vermont", abbr: "VT" },
  { county: "Essex County", state: "Vermont", abbr: "VT" },
  { county: "Franklin County", state: "Vermont", abbr: "VT" },
  { county: "Grand Isle County", state: "Vermont", abbr: "VT" },
  { county: "Lamoille County", state: "Vermont", abbr: "VT" },
  { county: "Orange County", state: "Vermont", abbr: "VT" },
  { county: "Orleans County", state: "Vermont", abbr: "VT" },
  { county: "Rutland County", state: "Vermont", abbr: "VT" },
  { county: "Washington County", state: "Vermont", abbr: "VT" },
  { county: "Windham County", state: "Vermont", abbr: "VT" },
  { county: "Windsor County", state: "Vermont", abbr: "VT" },
  // New Hampshire
  { county: "Belknap County", state: "New Hampshire", abbr: "NH" },
  { county: "Carroll County", state: "New Hampshire", abbr: "NH" },
  { county: "Cheshire County", state: "New Hampshire", abbr: "NH" },
  { county: "Coos County", state: "New Hampshire", abbr: "NH" },
  { county: "Grafton County", state: "New Hampshire", abbr: "NH" },
  { county: "Hillsborough County", state: "New Hampshire", abbr: "NH" },
  { county: "Merrimack County", state: "New Hampshire", abbr: "NH" },
  { county: "Rockingham County", state: "New Hampshire", abbr: "NH" },
  { county: "Strafford County", state: "New Hampshire", abbr: "NH" },
  { county: "Sullivan County", state: "New Hampshire", abbr: "NH" },
  // Maine
  { county: "Androscoggin County", state: "Maine", abbr: "ME" },
  { county: "Aroostook County", state: "Maine", abbr: "ME" },
  { county: "Cumberland County", state: "Maine", abbr: "ME" },
  { county: "Franklin County", state: "Maine", abbr: "ME" },
  { county: "Hancock County", state: "Maine", abbr: "ME" },
  { county: "Kennebec County", state: "Maine", abbr: "ME" },
  { county: "Knox County", state: "Maine", abbr: "ME" },
  { county: "Lincoln County", state: "Maine", abbr: "ME" },
  { county: "Oxford County", state: "Maine", abbr: "ME" },
  { county: "Penobscot County", state: "Maine", abbr: "ME" },
  { county: "Piscataquis County", state: "Maine", abbr: "ME" },
  { county: "Sagadahoc County", state: "Maine", abbr: "ME" },
  { county: "Somerset County", state: "Maine", abbr: "ME" },
  { county: "Waldo County", state: "Maine", abbr: "ME" },
  { county: "Washington County", state: "Maine", abbr: "ME" },
  { county: "York County", state: "Maine", abbr: "ME" },
  // Rhode Island
  { county: "Bristol County", state: "Rhode Island", abbr: "RI" },
  { county: "Kent County", state: "Rhode Island", abbr: "RI" },
  { county: "Newport County", state: "Rhode Island", abbr: "RI" },
  { county: "Providence County", state: "Rhode Island", abbr: "RI" },
  { county: "Washington County", state: "Rhode Island", abbr: "RI" },
];

// Group by state for the picker UI
export function countiesByState(): Record<string, CountyEntry[]> {
  return NORTHEAST_COUNTIES.reduce<Record<string, CountyEntry[]>>((acc, c) => {
    (acc[c.state] ??= []).push(c);
    return acc;
  }, {});
}
